/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedMastersSuppliersRouteImport } from './routes/_authenticated.masters.suppliers'
import { Route as AuthenticatedMastersPlantsRouteImport } from './routes/_authenticated.masters.plants'
import { Route as AuthenticatedMastersPipeSizesRouteImport } from './routes/_authenticated.masters.pipe-sizes'
import { Route as AuthenticatedMastersDepartmentsRouteImport } from './routes/_authenticated.masters.departments'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMastersSuppliersRoute =
  AuthenticatedMastersSuppliersRouteImport.update({
    id: '/masters/suppliers',
    path: '/masters/suppliers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMastersPlantsRoute =
  AuthenticatedMastersPlantsRouteImport.update({
    id: '/masters/plants',
    path: '/masters/plants',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMastersPipeSizesRoute =
  AuthenticatedMastersPipeSizesRouteImport.update({
    id: '/masters/pipe-sizes',
    path: '/masters/pipe-sizes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMastersDepartmentsRoute =
  AuthenticatedMastersDepartmentsRouteImport.update({
    id: '/masters/departments',
    path: '/masters/departments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/masters/departments': typeof AuthenticatedMastersDepartmentsRoute
  '/masters/pipe-sizes': typeof AuthenticatedMastersPipeSizesRoute
  '/masters/plants': typeof AuthenticatedMastersPlantsRoute
  '/masters/suppliers': typeof AuthenticatedMastersSuppliersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/masters/departments': typeof AuthenticatedMastersDepartmentsRoute
  '/masters/pipe-sizes': typeof AuthenticatedMastersPipeSizesRoute
  '/masters/plants': typeof AuthenticatedMastersPlantsRoute
  '/masters/suppliers': typeof AuthenticatedMastersSuppliersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/masters/departments': typeof AuthenticatedMastersDepartmentsRoute
  '/_authenticated/masters/pipe-sizes': typeof AuthenticatedMastersPipeSizesRoute
  '/_authenticated/masters/plants': typeof AuthenticatedMastersPlantsRoute
  '/_authenticated/masters/suppliers': typeof AuthenticatedMastersSuppliersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/masters/departments'
    | '/masters/pipe-sizes'
    | '/masters/plants'
    | '/masters/suppliers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/masters/departments'
    | '/masters/pipe-sizes'
    | '/masters/plants'
    | '/masters/suppliers'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/masters/departments'
    | '/_authenticated/masters/pipe-sizes'
    | '/_authenticated/masters/plants'
    | '/_authenticated/masters/suppliers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/masters/suppliers': {
      id: '/_authenticated/masters/suppliers'
      path: '/masters/suppliers'
      fullPath: '/masters/suppliers'
      preLoaderRoute: typeof AuthenticatedMastersSuppliersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/masters/plants': {
      id: '/_authenticated/masters/plants'
      path: '/masters/plants'
      fullPath: '/masters/plants'
      preLoaderRoute: typeof AuthenticatedMastersPlantsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/masters/pipe-sizes': {
      id: '/_authenticated/masters/pipe-sizes'
      path: '/masters/pipe-sizes'
      fullPath: '/masters/pipe-sizes'
      preLoaderRoute: typeof AuthenticatedMastersPipeSizesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/masters/departments': {
      id: '/_authenticated/masters/departments'
      path: '/masters/departments'
      fullPath: '/masters/departments'
      preLoaderRoute: typeof AuthenticatedMastersDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMastersDepartmentsRoute: typeof AuthenticatedMastersDepartmentsRoute
  AuthenticatedMastersPipeSizesRoute: typeof AuthenticatedMastersPipeSizesRoute
  AuthenticatedMastersPlantsRoute: typeof AuthenticatedMastersPlantsRoute
  AuthenticatedMastersSuppliersRoute: typeof AuthenticatedMastersSuppliersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMastersDepartmentsRoute: AuthenticatedMastersDepartmentsRoute,
  AuthenticatedMastersPipeSizesRoute: AuthenticatedMastersPipeSizesRoute,
  AuthenticatedMastersPlantsRoute: AuthenticatedMastersPlantsRoute,
  AuthenticatedMastersSuppliersRoute: AuthenticatedMastersSuppliersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
